// Stage-spec composer. Each opencode run is driven by a single markdown spec:
//
//   [_system.md]  shared workflow philosophy + conventions + language rule
//   [context]     runtime course state injected by the harness (meta, D-N,
//                 phase, file listings, target files) — so the agent doesn't
//                 re-discover what the harness already knows
//   [command]     the ported per-command instructions (assets/prompts/<x>.md)
//
// Templates use {{KEY}} placeholders filled from courseVars().
import { readPrompt, assetPath } from "./workspace.mjs";
import { interfaceLang, daysUntil, formatDN } from "./meta.mjs";
import { detectPhase, topMiss } from "./phase.mjs";

/** Replace every {{KEY}} in `text` with vars[KEY] (missing -> left as-is). */
export function interpolate(text, vars) {
  return text.replace(/\{\{([A-Z0-9_]+)\}\}/g, (m, k) => (k in vars ? String(vars[k]) : m));
}

/** Standard substitution vars derived from the course meta + workspace state. */
export function courseVars(root, meta, extra = {}) {
  const lang = interfaceLang(meta);
  const days = daysUntil(meta.EXAM_DATE);
  const vars = {
    COURSE_NAME: meta.COURSE_NAME || "course",
    EXAM_DATE: meta.EXAM_DATE || "unknown",
    EXAM_TYPE: meta.EXAM_TYPE || "exam",
    USER_WEAK_ZONES: meta.USER_WEAK_ZONES || "unknown",
    OCR_ENGINE: meta.OCR_ENGINE || "vision",
    INTERFACE_LANG: lang,
    DN: formatDN(days) || "D-?",
    PHASE: detectPhase(root, days),
    TOP_MISS: topMiss(root) || "—",
    ROOT: root,
    ASSET_SCRIPTS: assetPath("scripts"),
    ...extra,
  };
  return vars;
}

/** Render one "## <title>\n\n<body>" context block. */
function block(title, body) {
  return `## ${title}\n\n${body.trim()}\n`;
}

/**
 * Build the full stage spec text.
 *   promptFile      filename under assets/prompts/ (the command instructions)
 *   vars            from courseVars()
 *   contextSections array of { title, body } injected before the command
 *   includeSystem   prepend _system.md (default true)
 */
export function buildSpec({ promptFile, vars, contextSections = [], includeSystem = true }) {
  const parts = [];

  parts.push(
    `<!-- PAIDEIA stage spec — generated by the harness; executed by opencode. -->`,
    `# PAIDEIA — ${promptFile.replace(/\.md$/, "")} stage`,
    "",
  );

  if (includeSystem) {
    parts.push(interpolate(readPrompt("_system.md"), vars), "");
  }

  // Runtime course context the agent can trust.
  const ctx = [
    `- COURSE_NAME: ${vars.COURSE_NAME}`,
    `- EXAM: ${vars.EXAM_DATE} (${vars.DN}), type: ${vars.EXAM_TYPE}`,
    `- USER_WEAK_ZONES: ${vars.USER_WEAK_ZONES}`,
    `- OCR_ENGINE: ${vars.OCR_ENGINE}`,
    `- INTERFACE_LANG: ${vars.INTERFACE_LANG}  ← write all user-facing prose in this language`,
    `- Current phase: ${vars.PHASE}`,
    `- Workspace root: ${vars.ROOT}`,
  ].join("\n");
  parts.push(block("Course context (provided by the harness)", ctx));

  for (const s of contextSections) {
    if (s && s.body && String(s.body).trim()) parts.push(block(s.title, s.body));
  }

  parts.push("---", "");
  parts.push(interpolate(readPrompt(promptFile), vars));

  return parts.join("\n");
}
